name: allaw
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_screenutil: ^3.2.0
  share: ^0.6.5+4
  app_review: ^2.0.1
  advance_pdf_viewer: ^1.2.1+1
  http: ^0.12.2
  path_provider: ^1.6.24
  webview_flutter_plus: ^0.1.1+10
  firebase_core: ^0.5.1
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_storage: ^5.2.0
  excel: ^1.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/

