// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFNeNuUNlnn001i4MoIjBAPFlZWHqFHw',
    appId: '1:1029815375566:web:72313009d6a2643698a29f',
    messagingSenderId: '1029815375566',
    projectId: 'allaw-9cbd5',
    authDomain: 'allaw-9cbd5.firebaseapp.com',
    databaseURL: 'https://allaw-9cbd5-default-rtdb.firebaseio.com',
    storageBucket: 'allaw-9cbd5.appspot.com',
    measurementId: 'G-VSDK7H9L5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3d3xnLzf_dQc5Bt_1nz46U5751L_nNcc',
    appId: '1:1029815375566:android:f997c4aba722b3cb98a29f',
    messagingSenderId: '1029815375566',
    projectId: 'allaw-9cbd5',
    databaseURL: 'https://allaw-9cbd5-default-rtdb.firebaseio.com',
    storageBucket: 'allaw-9cbd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsLfC7xPf17-zFcC0MBG2HGoxlh0nASvs',
    appId: '1:1029815375566:ios:58df8657cbbbd59398a29f',
    messagingSenderId: '1029815375566',
    projectId: 'allaw-9cbd5',
    databaseURL: 'https://allaw-9cbd5-default-rtdb.firebaseio.com',
    storageBucket: 'allaw-9cbd5.appspot.com',
    iosClientId: '1029815375566-rlktb7fn99fc3o7tl7vfuk092npdevde.apps.googleusercontent.com',
    iosBundleId: 'com.lexliaise.allaw',
  );
}
